// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use a dummy URL during generation if DATABASE_URL is not set
    // This allows Prisma client generation without an actual database connection
    url: env("DATABASE_URL") || "postgresql://user:password@localhost:5432/dummy?schema=public",
  },
});
